    const namesOfAllah = {
        forgiveness: 'Al-Ghafoor (The Forgiving)',
        mercy: 'Ar-Rahman (The Most Merciful)',
        sustenance: 'Ar-Razzaq (The Provider)',
        protection: 'Al-Hafiz (The Preserver)',
        guidance: 'Al-Hadi (The Guide)',
        healing: 'Ash-Shafi (The Healer)',
        wisdom: 'Al-Hakim (The Wise)',
        patience: 'As-Sabur (The Patient)',
        success: 'Al-Fattah (The Opener)',
        justice: 'Al-Adl (The Just)',
        peace: 'As-Salam (The Source of Peace)',
        strength: 'Al-Qawi (The Strong)',
        love: 'Al-Wadud (The Loving)',
        knowledge: 'Al-Alim (The All-Knowing)',
        forgiveness_of_sins: 'Al-Afuww (The Pardoner)',
        wealth: 'Al-Ghani (The Self-Sufficient)',
        kindness: 'Ar-Ra’uf (The Kind)',
        repentance: 'At-Tawwab (The Acceptor of Repentance)',
        comfort: 'Al-Mu’min (The Giver of Peace)',
        control: 'Al-Malik (The King)',
        refuge: 'Al-Mannan (The Bestower)',
        hearing: 'As-Sami (The All-Hearing)',
        seeing: 'Al-Basir (The All-Seeing)',
        forgiveness_of_mistakes: 'Al-Afu (The Pardoner)',
        facilitation: 'Al-Muqaddim (The Expediter)',
        protection_from_harm: 'Al-Mani’ (The Preventer)',
        power: 'Al-Muqtadir (The Powerful)',
        compassion: 'Ar-Rahim (The Most Compassionate)',
        giving: 'Al-Wahhab (The Bestower)',
        acceptance: 'Al-Qabid (The Withholder)',
        expansion: 'Al-Basit (The Extender)',
        justice_and_fairness: 'Al-Adl (The Just)',
        protection_of_faith: 'Al-Mumin (The Giver of Faith)',
        generosity: 'Al-Karim (The Generous)',
        mercy_and_compassion: 'Ar-Rahman (The Most Merciful)',
        strength_and_power: 'Al-Qawi (The All-Strong)',
        provision: 'Ar-Razzaq (The Provider)',
        patience_and_fortitude: 'As-Sabur (The Patient)',
        sovereignty: 'Al-Malik (The King)',
        beauty: 'Al-Jamil (The Beautiful)',
        greatness: 'Al-Azim (The Great)',
        forgiveness_and_pardon: 'Al-Ghafur (The Forgiving)',
        vastness: 'Al-Wasi (The All-Embracing)',
        reward: 'Ash-Shakoor (The Grateful)',
        witness: 'Ash-Shaheed (The Witness)',
        guardian: 'Al-Wali (The Protecting Friend)',
        strength_and_might: 'Al-Matin (The Firm One)',
        knowledge_and_awareness: 'Al-Khabir (The All-Aware)',
        guidance_and_direction: 'Al-Hadi (The Guide)',
        understanding: 'Al-Fattah (The Opener)',
        existence_and_everlasting: 'Al-Hayy (The Ever-Living)',
        healing_and_cure: 'Ash-Shafi (The Healer)',
        hearing_and_listening: 'As-Sami (The All-Hearing)',
        sight_and_seeing: 'Al-Basir (The All-Seeing)',
        shaping_and_forming: 'Al-Bari (The Evolver)',
        planning_and_perfecting: 'Al-Musawwir (The Fashioner)',
        forgiveness_and_overlooking: 'Al-Ghafir (The Forgiver)',
        provision_and_sustenance: 'Ar-Razzaq (The Provider)',
        encompassing_and_wideness: 'Al-Muhit (The All-Encompassing)',
        protection_and_safety: 'Al-Hafiz (The Preserver)',
        beauty_and_excellence: 'Al-Jamil (The Beautiful)',
        encompassing_and_vastness: 'Al-Wasi (The All-Embracing)',
        power_and_strength: 'Al-Qadir (The Omnipotent)',
        guidance_and_leading: 'Ar-Rashid (The Guide to the Right Path)',
        perfection_and_completeness: 'Al-Kamil (The Perfect)',
        protection_and_defending: 'Al-Muhaymin (The Protector)',
        compassion_and_care: 'Ar-Ra’uf (The Kind)',
        mercy_and_benevolence: 'Ar-Rahim (The Merciful)',
        knowledge_and_wisdom: 'Al-Hakim (The Wise)',
        watchfulness_and_awareness: 'Ar-Raqib (The Watchful)',
        nobility_and_generosity: 'Al-Karim (The Generous)',
        return_and_resurrection: 'Al-Mu’id (The Restorer)'
    };

    function displayName() {
        const purpose = document.getElementById('purpose-select').value;
        const resultDiv = document.getElementById('result');
        
        if (purpose && namesOfAllah[purpose]) {
            resultDiv.textContent = `Call upon Allah by: ${namesOfAllah[purpose]}`;
        } else {
            resultDiv.textContent = '';
        }
    }
